name: CI GCES

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./aplicacao

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker-compose up --build
        working-directory: ${{env.working-directory}}

  test:
    runs-on: ubuntu-latest
    env:
      working-directory: ./aplicacao

    steps:
      - uses: actions/checkout@v3
      - name: Create database
        run: docker-compose run app bash -c "rake db:create; rake db:migrate; rake db:seed"
        working-directory: ${{env.working-directory}}
      - name: Reset database
        run: docker-compose run app bash -c "rake db:reset"
        working-directory: ${{env.working-directory}}
      - name: Run tests
        run: docker-compose run app rspec
        working-directory: ${{env.working-directory}}

  lint:
    runs-on: ubuntu-latest
    env:
      working-directory: ./aplicacao

    steps:
      - uses: actions/checkout@v3
      - name: Install and running rubocop
        run: docker-compose run app bash -c "gem install rubocop; rubocop -l --fail-level F"
        working-directory: ${{env.working-directory}}
